version: "3.0"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cpu_count: 262144
    ports:
      - "9200:9200"
